### ISSUE TITLE
Add "delete" command to the CLI

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#167]
I would like to see a "delete" command added to the Meli CLI that deletes the deploy of a specific branch. In my use-case, which is deploying branches via CI as previews, each PR generates a deploy, and I would like to be able to automatically clean it up once the PR gets closed. Right now I have to head over into the UI to click the delete button.

**Comment by gempain** [comment]
Aww, yup, that's a good one too. Just quickly brainstorming before going deeper, how would we detect that the PR has been closed ? When the PR is merged, a CI pipeline runs for the base branch, and in there I don't think we can tell which PR has been merged, do we ? GH Actions sets `GITHUB_HEAD_REF ` and `GITHUB_BASE_REF ` as an [environment variable](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables), but I don't think their available once running on the base branch.

We could add a `--delete-branch` CLI option which would let you specify the branches to delete, but it feels bit unsafe, no ? I mean, you still have to get access to the token, which indicates you have access to the site, but that leak could come from other places.

The cleanest approach I can think of is to setup webhooks on your Git server to let Meli know when a PR is closed, but I don't want to create this dependency at the moment, it's too early and there's a bunch of test coverage to increase before adding extra dependencies.

Do you have an idea of how we would implement this ?

**Comment by queicherius** [comment]
I was thinking of having a separate workflow, similar to this (untested, pseudo-code)

```yaml
name: Continuous Integration

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: 'Cleanup'
    runs-on: ubuntu-latest

    steps:
      - name: 'Cleanup deploy (documentation)'
        run: |
          npx @getmeli/cli@next delete \
            --url "https://meli.company.io" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --branch "$GITHUB_BRANCH"
        env:
          MELI_SITE: '<site uuid>'
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_BRANCH: ${{ github.payload.pull_request.head.ref }}
```
