### ISSUE TITLE
CLI configuration file

### ISSUE THREAD

**Issue by gempain** [getmeli/meli#182]
Credits to @robertorubioguardia for suggesting this feature.

It would be nice to have a `.melirc` configuration file. For example:

```yaml
version: 1
upload:
  siteId: 123
  token: token
  url: https://meli.domain.com
```

and then

```sh
@getmeli/cli upload ./dir
```

This file could be source from:
- the current directory
- the home directory
- the `--config` CLI option
