### ISSUE TITLE
GH Action Error: Cannot open assembly 'upload'

### ISSUE THREAD

**Issue by Berndinox** [getmeli/meli#209]
Error Message:
```
Run npx @getmeli/cli upload \
  npx @getmeli/cli upload \
    --url "https://meli.DOMAIN.at" \
    --site "$MELI_SITE" \
    --token "$MELI_TOKEN" \
    --release "$GITHUB_SHA" \
    ./public
  shell: /usr/bin/bash -e {0}
  env:
    MELI_SITE: ebbcef92-c923-4bfc-bdf1-605a6b275f3e
    MELI_TOKEN: ***
    GITHUB_TOKEN: ***
Cannot open assembly 'upload': No such file or directory.
Error: Process completed with exit code 2.
```

Github Action:
```
name: main
on: [ push ]
env:
  MELI_SITE: "SITEID"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: "build"
        run: |
          npm install
          npm run build
      - name: "publish"
        run: |
          npx @getmeli/cli upload \
            --url "https://meli.DOMAIN.at" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA" \
            ./public
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          # Enable PR previews:
          # uses the default GITHUB_TOKEN set by Github Actions
          # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
